import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ecomm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <p>Main</p>
				<Link href="/signup/signup" >Signup</Link>
				<Link href="/signin/signin" >Sign In</Link>
				<Link href="/shoppingcart/mycart" >My Cart</Link>
				<Link href="/products/all/allproducts" >All Products</Link>
      </main>

      <footer className={styles.footer}>
				<p>Footer</p>
      </footer>
    </div>
  )
}
