import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import Featured from "../components/Featured";
import RecentlyViewed from "../components/RecentlyViewed";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ecomm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div>
          <Featured />
        </div>
				<div>
					<RecentlyViewed />
				</div>
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
